#!/usr/bin/env bash
# configures a new HAproxy as a load balancer

# Install HAproxy on a server
apt-get -y update
apt-get -y install haproxy=1.6.\*

# Configure haproxy configuration file to distribute requests using a roundrobin algorithm
echo '
frontend villlageofgold.tech
        bind 0:80
        default_backend web_servers

backend web_servers
        balance roundrobin
        server 108925-web-01 54.157.156.30
        server 108925-web-02 100.25.146.12
' >> /etc/haproxy/haproxy.cfg

# Restart HAproxy service
service haproxy restart
